# Generated by Django 5.1.5 on 2025-02-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprogress',
            name='game_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
