# Generated by Django 5.1.5 on 2025-02-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_gameprogress_game_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcidInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=55)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecksonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=55)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
