# Generated by Django 5.1.5 on 2025-02-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_acidinfo_recksoninfo_delete_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='acidinfo',
            name='tg_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='acidinfo',
            name='vk_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recksoninfo',
            name='tg_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recksoninfo',
            name='vk_link',
            field=models.URLField(blank=True),
        ),
    ]
